### ISSUE TITLE
Add summoning result to finished summon entity

### ISSUE THREAD

**Issue by wyze** [TreasureProject/treasure-subgraphs#50]

**Comment by alecananian** [comment]
Summons are actually being completely removed when they're finished. Should that not be the case?

https://github.com/TreasureProject/treasure-subgraphs/blob/master/subgraphs/bridgeworld/src/mappings/summoning.ts#L85

**Comment by wyze** [comment]
No it is correct, it is saved with a new id, and status Finished. It's so we can easily create a new one with id of `{event.address}-{tokenId}`.

**Comment by alecananian** [comment]
Ah got it - I see that new `id` assignment now.
