### ISSUE TITLE
Remove blank treasure from CraftingStats

### ISSUE THREAD

**Issue by 0xkarel** [TreasureProject/treasure-subgraphs#87]
There's an empty treasure in the list of treasures when you run this query:

```
{
  craftingStat(id: "all-time") {
    treasureStats {
      name
      tier
      craftingUsed
      craftingBroken
    }
  }
}
```

<img width="239" alt="image" src="https://user-images.githubusercontent.com/95452264/155868364-9fbce183-f9b3-47c8-ab0f-5ed90923a5ee.png">

**Comment by alecananian** [comment]
@0xkarel this is fixed in the production subgraph now
